server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  port: 8081

spring:
  security:
    user:
      name: administrator
      password: administrator
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://licapp-postgres:5432/lis_dbms
    username: licuser
    password: h4IK98KGFgcF
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        check_nullability: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    redis:
      host: licapp-redis
      port: 6379
    rest:
      default-page-size: 100000
      base-path: /data

javers:
  sqlSchema: audit
  sql:
    dialect: hibernate # Use hibernate for other database
  commitIdGenerator: SYNCHRONIZED_SEQUENCE
  snapshotsCacheSize: 1000

jwt:
  secret: aOPQaAa8NY5tY8mvQve7xkVn06bSn9/3kkjSUh8mD37UdhRBULQydMwmqRqLcMxOoiqVBOq4VxIo9mQptcPeUA==


frontend:
  url: https://lic.mci.gov.tl
logging:
  level:
    tl.gov.mci.lic: DEBUG
    org.springframework: ERROR

sentry:
  dsn: https://78cf24ba710171f500db72b2f924b9b1@o4509671470006272.ingest.de.sentry.io/4509671477084240
  send-default-pii: true
  environment: production
  debug: false                  # to see internal SDK logs during setup/testing
  logging:
    enabled: false              # capture logs
    minimum-event-level: error
    minimum-breadcrumb-level: info
  exception-resolver-order: -2147483647
  ignored-exceptions-for-type:
    - tl.gov.mci.lis.exceptions.ResourceNotFoundException
    - tl.gov.mci.lis.exceptions.ForbiddenException
    - tl.gov.mci.lis.exceptions.AlreadyExistException
    - tl.gov.mci.lis.exceptions.FileDownloadUploadException
    - tl.gov.mci.lis.exceptions.BadRequestException
minio:
  url: http://licapp-minio:9000
  accessKey: licapp-user
  secretKey: 2WVEyRSKiUsF
  bucket: mci-lis
  region: us-east-1
management:
  endpoints:
    web:
      base-path: /follow
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      access: read_only